apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdapv
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/
