apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: todoapp
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/
