apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  namespace: todoapp
spec:
  storageClassName: standart
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/
