apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-todoapp
  namespace: todoapp
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp/data/todoapp
