apiVersion: v1
kind: PersistentVolume
metadata:
  name: todoapp-pv
  namespace: todoapp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /mnt/data
