apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-todoapp
  namespace: mateapp
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/