apiVersion: v1
kind: PersistentVolume
metadata: 
  name: todoapp-pv
  namespace: todoapp
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:  
  - ReadWriteMany
  capacity: 
    storage: 1Gi
  hostPath:
    path: /app/data/
