apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-todoapp
  namespace: todoapp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /tmp/data/todoapp


