apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-data
 namespace: todoapp
 spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  accessModes:
   - ReadWriteMany
  capacity:
   storage: 1Gi
  hostPath:
   path: /data/
