apiVersion: v1
kind: PersistentVolume
metadata:
  name: todoapp-pv
  namespace: todoapp
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/
