apiVersion: v1
kind: PersistentVolume
metadata:
  name: todoapp-pv
  namespace: todoapp
spec:
  capacity:
    storage: 1 Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /tmp/data/todoapp
