apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume
  namespace: todoapp
spec:
  volumeName: pv-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
