apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: todoapp
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
