apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: todoapp
spec:
  storageClassName: standard
  volumeName: pv-data
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
