apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-todoapp
  namespace: mateapp
spec:
  volumeName: pv-todoapp
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
