apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: todoapp
spec:
  resources:
    requests:
      storage:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: standard
