apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todoapp-pvc
  namespace: todoapp
spec:
  volumeName: todoapp-pv
  resources:
    requests:
      storage: 1Gi
  accessModes: ["ReadWriteMany"]