apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todoapp-pvc
  namespace: todoapp
spec:
  volumeName: todoapp-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
